services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SERVICE_HOST: "0.0.0.0"
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    depends_on:
      - redis

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest

volumes:
  redis:
  postgres:
